// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {library} from '../models';
import {tagging} from '../models';
import {exporter} from '../models';

export function ActiveOperations():Promise<app.OperationListResponse>;

export function ApplicationStatus():Promise<app.StatusResponse>;

export function CancelOperation(arg1:string):Promise<app.OperationResponse>;

export function CreateShelf(arg1:string,arg2:library.StoryLibraryQuery):Promise<app.ShelfResponse>;

export function CreateTagDefinition(arg1:tagging.CreateDefinition):Promise<app.TagDefinitionResponse>;

export function CreateTagValue(arg1:tagging.CreateValue):Promise<app.TagValueResponse>;

export function DeleteShelf(arg1:number):Promise<app.MutationResponse>;

export function DeleteTagDefinition(arg1:tagging.DefinitionDeletionPlan):Promise<app.MutationResponse>;

export function DeleteTagValue(arg1:tagging.ValueDeletionPlan):Promise<app.MutationResponse>;

export function DuplicateShelf(arg1:number,arg2:string):Promise<app.ShelfResponse>;

export function ListShelves():Promise<app.ShelfListResponse>;

export function ListStories(arg1:library.ListRequest):Promise<app.LibraryPageResponse>;

export function OfficialMetadataStatus():Promise<app.MetadataStatusResponse>;

export function OpenShelf(arg1:number,arg2:library.ListRequest):Promise<app.ShelfEvaluationResponse>;

export function OperationSnapshot(arg1:string):Promise<app.OperationResponse>;

export function PlanTagDefinitionDeletion(arg1:number):Promise<app.TagDefinitionDeletionPlanResponse>;

export function PlanTagValueDeletion(arg1:number):Promise<app.TagValueDeletionPlanResponse>;

export function PreviewShelves(arg1:Array<number>):Promise<app.ShelfSelectionPreviewResponse>;

export function QueryStories(arg1:library.StoryLibraryQuery):Promise<app.LibraryPageResponse>;

export function RecolorTagDefinition(arg1:number,arg2:string):Promise<app.TagDefinitionResponse>;

export function RefreshOfficialMetadata():Promise<app.OperationResponse>;

export function RemoveStory(arg1:number):Promise<app.RemovalResponse>;

export function RenameShelf(arg1:number,arg2:string):Promise<app.ShelfResponse>;

export function RenameTagDefinition(arg1:number,arg2:string):Promise<app.TagDefinitionResponse>;

export function RenameTagValue(arg1:number,arg2:string):Promise<app.TagValueResponse>;

export function ReorderShelves(arg1:Array<number>):Promise<app.ShelfListResponse>;

export function ReorderTagDefinitions(arg1:Array<number>):Promise<app.MutationResponse>;

export function ReorderTagValues(arg1:number,arg2:Array<number>):Promise<app.MutationResponse>;

export function ReplaceShelfQuery(arg1:number,arg2:library.StoryLibraryQuery):Promise<app.ShelfResponse>;

export function RevealExportDestination(arg1:string):Promise<app.MutationResponse>;

export function SelectAndImportStories():Promise<app.OperationResponse>;

export function SelectAndPreflightExport(arg1:exporter.PreflightRequest):Promise<app.ExportPreflightResponse>;

export function SetBooleanTag(arg1:Array<number>,arg2:number,arg3:boolean):Promise<app.TagAssignmentResponse>;

export function SetChoiceTagValue(arg1:Array<number>,arg2:number,arg3:number,arg4:boolean):Promise<app.TagAssignmentResponse>;

export function SetChoiceTagValues(arg1:Array<number>,arg2:number,arg3:Array<number>):Promise<app.TagAssignmentResponse>;

export function StartPreparedExport(arg1:string):Promise<app.OperationResponse>;

export function StoryDetail(arg1:number):Promise<app.StoryDetailResponse>;

export function TagAssignmentWorkspace(arg1:Array<number>):Promise<app.TagAssignmentWorkspaceResponse>;

export function TagCatalog():Promise<app.TagCatalogResponse>;
