// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {library} from '../models';

export function ActiveOperations():Promise<app.OperationListResponse>;

export function ApplicationStatus():Promise<app.StatusResponse>;

export function CancelOperation(arg1:string):Promise<app.OperationResponse>;

export function ListStories(arg1:library.ListRequest):Promise<app.LibraryPageResponse>;

export function OperationSnapshot(arg1:string):Promise<app.OperationResponse>;

export function RemoveStory(arg1:number):Promise<app.RemovalResponse>;

export function SelectAndImportStories():Promise<app.OperationResponse>;

export function StoryDetail(arg1:number):Promise<app.StoryDetailResponse>;
