// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplicationStatus() {
  return window['go']['main']['App']['ApplicationStatus']();
}

export function CancelOperation(arg1) {
  return window['go']['main']['App']['CancelOperation'](arg1);
}

export function ListStories(arg1) {
  return window['go']['main']['App']['ListStories'](arg1);
}

export function OperationSnapshot(arg1) {
  return window['go']['main']['App']['OperationSnapshot'](arg1);
}

export function RemoveStory(arg1) {
  return window['go']['main']['App']['RemoveStory'](arg1);
}

export function SelectAndImportStories() {
  return window['go']['main']['App']['SelectAndImportStories']();
}

export function StoryDetail(arg1) {
  return window['go']['main']['App']['StoryDetail'](arg1);
}
