// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActiveOperations() {
  return window['go']['main']['App']['ActiveOperations']();
}

export function ApplicationStatus() {
  return window['go']['main']['App']['ApplicationStatus']();
}

export function CancelOperation(arg1) {
  return window['go']['main']['App']['CancelOperation'](arg1);
}

export function CreateTagDefinition(arg1) {
  return window['go']['main']['App']['CreateTagDefinition'](arg1);
}

export function CreateTagValue(arg1) {
  return window['go']['main']['App']['CreateTagValue'](arg1);
}

export function DeleteTagDefinition(arg1) {
  return window['go']['main']['App']['DeleteTagDefinition'](arg1);
}

export function DeleteTagValue(arg1) {
  return window['go']['main']['App']['DeleteTagValue'](arg1);
}

export function ListStories(arg1) {
  return window['go']['main']['App']['ListStories'](arg1);
}

export function OfficialMetadataStatus() {
  return window['go']['main']['App']['OfficialMetadataStatus']();
}

export function OperationSnapshot(arg1) {
  return window['go']['main']['App']['OperationSnapshot'](arg1);
}

export function PlanTagDefinitionDeletion(arg1) {
  return window['go']['main']['App']['PlanTagDefinitionDeletion'](arg1);
}

export function PlanTagValueDeletion(arg1) {
  return window['go']['main']['App']['PlanTagValueDeletion'](arg1);
}

export function QueryStories(arg1) {
  return window['go']['main']['App']['QueryStories'](arg1);
}

export function RecolorTagDefinition(arg1, arg2) {
  return window['go']['main']['App']['RecolorTagDefinition'](arg1, arg2);
}

export function RefreshOfficialMetadata() {
  return window['go']['main']['App']['RefreshOfficialMetadata']();
}

export function RemoveStory(arg1) {
  return window['go']['main']['App']['RemoveStory'](arg1);
}

export function RenameTagDefinition(arg1, arg2) {
  return window['go']['main']['App']['RenameTagDefinition'](arg1, arg2);
}

export function RenameTagValue(arg1, arg2) {
  return window['go']['main']['App']['RenameTagValue'](arg1, arg2);
}

export function ReorderTagDefinitions(arg1) {
  return window['go']['main']['App']['ReorderTagDefinitions'](arg1);
}

export function ReorderTagValues(arg1, arg2) {
  return window['go']['main']['App']['ReorderTagValues'](arg1, arg2);
}

export function SelectAndImportStories() {
  return window['go']['main']['App']['SelectAndImportStories']();
}

export function SetBooleanTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBooleanTag'](arg1, arg2, arg3);
}

export function SetChoiceTagValue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetChoiceTagValue'](arg1, arg2, arg3, arg4);
}

export function SetChoiceTagValues(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetChoiceTagValues'](arg1, arg2, arg3);
}

export function StoryDetail(arg1) {
  return window['go']['main']['App']['StoryDetail'](arg1);
}

export function TagAssignmentWorkspace(arg1) {
  return window['go']['main']['App']['TagAssignmentWorkspace'](arg1);
}

export function TagCatalog() {
  return window['go']['main']['App']['TagCatalog']();
}
